### ISSUE TITLE
rendering order

### ISSUE THREAD

**Issue by JustLian** [JustLian/osu-python#19]
1. Adding objects to queue
2. Reversing queue
3. Rendering objects

**Comment by Filo6699** [comment]
The queue of objects is now reversed, but there is another issue. Approach circles.

![Image](https://user-images.githubusercontent.com/114665857/218262467-7cc4d7ce-e725-4cdc-89c2-a36004d90012.png)

This is solvable if we will render object parts one by one
First we render all of the hit circles with their overlays
And then we iterate though queue again and render approach circles
