### ISSUE TITLE
sliders

### ISSUE THREAD

**Issue by JustLian** [JustLian/osu-python#5]
[Sliders render preview](https://gist.github.com/Filo6699/2ef0416f16cb8a6db411224e48a06c70)
Sliders rendering method wouldn't be added to main app until proper optimization release. For now, render time of all frames with sliders is really long. We should either optimize process somehow or pre-render some sliders while loading beatmap

- [ ] render method for slider's body
- [ ] slider's scores

**Comment by Filo6699** [comment]
Updated gist.
New method for rendering sliders turned out to be extremely effective
