### ISSUE TITLE
stacked circles

### ISSUE THREAD

**Issue by JustLian** [JustLian/osu-python#7]
if map has any stacked circles, play can't press them. Tried to fix this issue in upcoming commit. Not its better, but still isn't working

**Comment by JustLian** [comment]
837d9645419900bcf5961099efaa9b9afc77ac57

**Comment by Filo6699** [comment]
Player can now press stacked cirlces, but note lock and hit windows issues make that if you missed 1 note in a stream, you are not able to hit any note in that stream

**Comment by JustLian** [comment]
no idea how to fix it 💀 @suvoshi any thoughts?

**Comment by Filo6699** [comment]
210375924a553bd47b1e720e37edcc697c553890
